# Generated by Django 4.2.16 on 2026-07-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'argument_assignments',
            },
        ),
        migrations.CreateModel(
            name='ClusterRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(blank=True, default='', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('n_reels', models.IntegerField(default=0)),
                ('n_clusters', models.IntegerField(default=0)),
                ('n_noise', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=16)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cluster_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=32, unique=True)),
                ('ig_media_id', models.CharField(blank=True, default='', max_length=64)),
                ('caption', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('thumbnail_file', models.CharField(blank=True, default='', max_length=255)),
                ('audio_file', models.CharField(blank=True, default='', max_length=255)),
                ('audio_info', models.JSONField(blank=True, default=dict)),
                ('raw_json_path', models.CharField(blank=True, default='', max_length=255)),
                ('media_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('transcribe_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('enrich_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('argument_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('media_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reels',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraper_config',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=7)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('ig_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('profile_pic_url', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('scrape_state', models.JSONField(blank=True, default=dict)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tracked_accounts',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='it', max_length=8)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('audio_duration_s', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='core.reel')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_it', models.CharField(blank=True, default='', max_length=120)),
                ('description_it', models.TextField(blank=True, default='')),
                ('size', models.IntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('centroid', models.JSONField(blank=True, default=list)),
                ('position', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.clusterrun')),
            ],
            options={
                'db_table': 'topic_clusters',
                'ordering': ['-size'],
            },
        ),
        migrations.CreateModel(
            name='ReelEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.reel')),
            ],
            options={
                'db_table': 'reel_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ReelClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reel_assignments', to='core.topiccluster')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to='core.reel')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_assignments', to='core.clusterrun')),
            ],
            options={
                'db_table': 'reel_cluster_assignments',
            },
        ),
        migrations.CreateModel(
            name='ReelArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_it', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.reel')),
            ],
            options={
                'db_table': 'reel_arguments',
            },
        ),
        migrations.CreateModel(
            name='ReelAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_inspiration', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='core.reel')),
                ('tags', models.ManyToManyField(blank=True, related_name='annotations', to='core.tag')),
            ],
            options={
                'db_table': 'reel_annotations',
            },
        ),
        migrations.AddField(
            model_name='reel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='core.trackedaccount'),
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_it', models.TextField(blank=True, default='')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('hook_text', models.TextField(blank=True, default='')),
                ('hook_analysis_it', models.TextField(blank=True, default='')),
                ('target_audience_it', models.TextField(blank=True, default='')),
                ('content_format', models.CharField(blank=True, choices=[('talking_head', 'Talking head'), ('voiceover', 'Voiceover'), ('tutorial', 'Tutorial'), ('testimonianza', 'Testimonianza'), ('text_overlay', 'Text overlay'), ('intervista', 'Intervista'), ('altro', 'Altro')], default='', max_length=32)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='core.reel')),
            ],
            options={
                'db_table': 'enrichments',
            },
        ),
        migrations.AddIndex(
            model_name='clusterrun',
            index=models.Index(fields=['is_current'], name='cluster_run_is_curr_b14071_idx'),
        ),
        migrations.AddField(
            model_name='argumentassignment',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.reelargument'),
        ),
        migrations.AddField(
            model_name='argumentassignment',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='argument_assignments', to='core.topiccluster'),
        ),
        migrations.AddField(
            model_name='argumentassignment',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argument_assignments', to='core.clusterrun'),
        ),
        migrations.AlterUniqueTogether(
            name='reelclusterassignment',
            unique_together={('run', 'reel')},
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['media_status'], name='reels_media_s_d67090_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['transcribe_status'], name='reels_transcr_28e1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['enrich_status'], name='reels_enrich__8b7779_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['argument_status'], name='reels_argumen_09950f_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-posted_at'], name='reels_posted__92a685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='argumentassignment',
            unique_together={('run', 'argument')},
        ),
    ]
