# Generated by Django 4.2.16 on 2026-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedaccount',
            name='owner_type',
            field=models.CharField(choices=[('competitor', 'competitor'), ('owned', 'owned')], default='competitor', max_length=16),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('blog', 'Blog'), ('manual', 'Manual'), ('other', 'Other')], default='blog', max_length=16)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content_md', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary_it', models.TextField(blank=True, default='')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('enrich_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('embed_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['enrich_status'], name='knowledge_d_enrich__910039_idx'), models.Index(fields=['embed_status'], name='knowledge_d_embed_s_d1e114_idx')],
            },
        ),
    ]
