# Generated by Django 4.2.16 on 2026-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trackedaccount_owner_type_knowledgedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_it', models.CharField(max_length=300)),
                ('rationale_it', models.TextField(blank=True, default='')),
                ('angle_it', models.TextField(blank=True, default='')),
                ('is_gap', models.BooleanField(default=False)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='proposed', max_length=16)),
                ('batch', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='clusterrun',
            name='cluster_run_is_curr_b14071_idx',
        ),
        migrations.AddField(
            model_name='clusterrun',
            name='scope',
            field=models.CharField(choices=[('competitor', 'competitor'), ('owned', 'owned')], default='competitor', max_length=16),
        ),
        migrations.AddIndex(
            model_name='clusterrun',
            index=models.Index(fields=['scope', 'is_current'], name='cluster_run_scope_b5d444_idx'),
        ),
        migrations.AddIndex(
            model_name='contentidea',
            index=models.Index(fields=['status'], name='content_ide_status_2f515e_idx'),
        ),
    ]
