# Generated by Django 4.2.16 on 2026-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contentidea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_status_92f544_idx')],
            },
        ),
    ]
