# Generated by Django 4.2.16 on 2026-07-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('expand', 'Expand existing'), ('draft', 'New draft')], max_length=12)),
                ('cluster_label', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content_md', models.TextField(blank=True, default='')),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='proposed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog')], max_length=24),
        ),
        migrations.CreateModel(
            name='DocClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_assignments', to='core.topiccluster')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to='core.knowledgedocument')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_assignments', to='core.clusterrun')),
            ],
            options={
                'db_table': 'doc_cluster_assignments',
                'unique_together': {('run', 'document')},
            },
        ),
    ]
