# Generated by Django 4.2.16 on 2026-07-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogdraft_alter_job_kind_docclusterassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=400)),
                ('source_kind', models.CharField(default='input', max_length=16)),
                ('coverage', models.CharField(choices=[('covered', 'Covered'), ('partial', 'Partial'), ('gap', 'Gap')], default='gap', max_length=12)),
                ('brief_md', models.TextField(blank=True, default='')),
                ('draft_md', models.TextField(blank=True, default='')),
                ('medyca_sources', models.JSONField(blank=True, default=list)),
                ('competitor_sources', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='proposed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_briefs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog'), ('strategy', 'Strategy'), ('strategy_draft', 'Strategy draft')], max_length=24),
        ),
    ]
