# Generated by Django 4.2.16 on 2026-07-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_strategybrief_alter_job_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_topics',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CustomTopicMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='competitor', max_length=16)),
                ('similarity', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_topic_matches', to='core.knowledgedocument')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_topic_matches', to='core.reel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.customtopic')),
            ],
            options={
                'db_table': 'custom_topic_matches',
                'indexes': [models.Index(fields=['topic', 'scope'], name='custom_topi_topic_i_21f15e_idx')],
            },
        ),
    ]
