# Generated by Django 4.2.16 on 2026-07-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customtopic_customtopicmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtopicmatch',
            name='via',
            field=models.CharField(default='semantic', max_length=16),
        ),
    ]
