# Generated by Django 4.2.16 on 2026-07-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customtopicmatch_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='evidence',
            field=models.CharField(choices=[('transcript', 'transcript'), ('caption_only', 'caption_only'), ('insufficient', 'insufficient')], default='transcript', max_length=16),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='is_on_topic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='off_topic_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='reelargument',
            name='quote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
