# Generated by Django 4.2.16 on 2026-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enrichment_evidence_enrichment_is_on_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdraft',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='strategybrief',
            name='brief_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='strategybrief',
            name='draft_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
