# Generated by Django 4.2.16 on 2026-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogdraft_llm_model_strategybrief_brief_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='primary_topic',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
