# Generated by Django 4.2.16 on 2026-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enrichment_primary_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='content_format',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='hook_it',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='scope',
            field=models.CharField(default='owned', max_length=16),
        ),
    ]
