# Generated by Django 4.2.16 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contentidea_content_format_contentidea_hook_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='cta_it',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='outline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog'), ('strategy', 'Strategy'), ('strategy_draft', 'Strategy draft'), ('editorial', 'editorial')], max_length=24),
        ),
    ]
