# Generated by Django 4.2.16 on 2026-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contentidea_cta_it_contentidea_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='chunk_vectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reelembedding',
            name='chunk_vectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
