# Generated by Django 4.2.16 on 2026-07-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_knowledgedocument_chunk_vectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='argument_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_on_topic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='off_topic_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='owner_type',
            field=models.CharField(choices=[('competitor', 'competitor'), ('owned', 'owned')], db_index=True, default='owned', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='primary_topic',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog'), ('strategy', 'Strategy'), ('strategy_draft', 'Strategy draft'), ('editorial', 'editorial'), ('blogsource_discover', 'Blog source discovery')], max_length=24),
        ),
        migrations.CreateModel(
            name='DocumentArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_it', models.TextField()),
                ('quote', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.knowledgedocument')),
            ],
            options={
                'db_table': 'document_arguments',
            },
        ),
        migrations.CreateModel(
            name='BlogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_url', models.URLField(blank=True, default='', max_length=300)),
                ('index_url', models.URLField(max_length=500, unique=True)),
                ('owner_type', models.CharField(choices=[('competitor', 'competitor'), ('owned', 'owned')], default='competitor', max_length=16)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('crawl_interval_h', models.IntegerField(default=168)),
                ('strategy', models.CharField(choices=[('unknown', 'unknown'), ('sitemap', 'sitemap'), ('feed', 'feed'), ('index', 'index'), ('mixed', 'mixed')], default='unknown', max_length=16)),
                ('discovery', models.JSONField(blank=True, default=dict)),
                ('crawl_state', models.JSONField(blank=True, default=dict)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'owner_type'], name='blog_source_is_acti_26f4a1_idx')],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.blogsource'),
        ),
    ]
