# Generated by Django 4.2.16 on 2026-08-07 19:02

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_medyca_blog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog'), ('strategy', 'Strategy'), ('strategy_draft', 'Strategy draft'), ('editorial', 'editorial'), ('blogsource_discover', 'Blog source discovery'), ('upload_transcribe', 'Upload transcribe')], max_length=24),
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models._upload_path)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=8)),
                ('original_name', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('audio_file', models.CharField(blank=True, default='', max_length=500)),
                ('transcribe_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='core.blogdraft')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='core.knowledgedocument')),
            ],
            options={
                'db_table': 'uploaded_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
