# Generated by Django 4.2.16 on 2026-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_job_kind_uploadedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
