# Generated by Django 4.2.16 on 2026-08-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reelembedding_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
