# Generated by Django 4.2.16 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_knowledgedocument_tags_tag_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='argument_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='embed_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='enrich_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reel',
            name='argument_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reel',
            name='enrich_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reel',
            name='media_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reel',
            name='transcribe_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='transcribe_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped'), ('batched', 'batched')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enrich', 'enrich')], default='enrich', max_length=16)),
                ('batch_id', models.CharField(max_length=120, unique=True)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('ended', 'ended'), ('collected', 'collected'), ('failed', 'failed'), ('canceled', 'canceled')], default='submitted', max_length=16)),
                ('items', models.JSONField(blank=True, default=list)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_runs',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='batch_runs_status_5ccabc_idx')],
            },
        ),
    ]
