# Generated by Django 4.2.16 on 2026-09-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_knowledgedocument_argument_status_and_more'),
    ]

    def _rename_enrich(apps, schema_editor):
        """The first batches were all reel analyses under the name "enrich".
        Renaming them keeps collect() able to recognise its own history —
        an unknown kind would be skipped and its rows left in `batched`."""
        apps.get_model("core", "BatchRun").objects.filter(kind="enrich").update(
            kind="reel_enrich")

    operations = [
        migrations.AlterField(
            model_name='batchrun',
            name='kind',
            field=models.CharField(choices=[('reel_enrich', 'analisi di un reel'), ('doc_enrich', 'analisi di un articolo'), ('doc_arguments', 'affermazioni di un articolo')], default='reel_enrich', max_length=20),
        ),
        migrations.RunPython(_rename_enrich, migrations.RunPython.noop),
    ]
