# Generated by Django 4.2.16 on 2026-09-13 18:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_batchrun_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_inspiration',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='is_inspiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='owner_type',
            field=models.CharField(choices=[('owned', 'owned'), ('competitor', 'competitor')], default='owned', max_length=16),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pipeline', 'Pipeline'), ('blog', 'Blog'), ('strategy', 'Strategy'), ('strategy_draft', 'Strategy draft'), ('editorial', 'editorial'), ('blogsource_discover', 'Blog source discovery'), ('upload_transcribe', 'Upload transcribe'), ('link_transcribe', 'Link transcribe')], max_length=24),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='source_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('manual', 'Manual'), ('video', 'Video'), ('other', 'Other')], default='blog', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='file',
            field=models.FileField(blank=True, upload_to=core.models._upload_path),
        ),
    ]
